name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Generate Docs
        run: ./gradlew docs
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: build/docs
          branch: docs
